# seam-scope: public-seam (structural skill scaffold generated by a package build)
from __future__ import annotations

from pathlib import Path

import docops

GUIDE = """# Authentication

Send credentials with every request.

```python
# Send the request, with a custom header.
client = Client()
```

## Custom flows

~~~sh
# not a heading either
~~~
"""


def test_comments_inside_code_blocks_are_not_chapter_sections(tmp_path: Path) -> None:
    source = tmp_path / "source"
    source.mkdir()
    (source / "auth.md").write_text(GUIDE, encoding="utf-8")
    (source / "hooks.md").write_text(
        "```python\n# Log every request.\nlog(request)\n```\n\n## Event hooks\n\nHooks run per request.\n",
        encoding="utf-8",
    )
    output = tmp_path / "package"

    result = docops.apply(
        docops.plan(
            docops.OperationRequest(
                source,
                docops.OperationOptions(output_dir=output, source_root=source.parent, slug="acme", license="MIT"),
            )
        )
    )

    assert result.ok, result.errors
    chapters = sorted(path.name for path in (output / "skill" / "chapters").glob("*.md"))
    assert chapters == ["01-authentication.md", "02-event-hooks.md"]
    chapter = (output / "skill" / "chapters" / "01-authentication.md").read_text(encoding="utf-8")
    assert "- Authentication" in chapter and "- Custom flows" in chapter
    assert "Send the request" not in chapter and "not a heading" not in chapter
